sudo: required
services:
  -docker

before_install:
  - docker build -t apptest:1 -f Dockerfile.dev .

script:
  - docker run apptest:1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "bcdocker"
  env: "bcdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-118363283813" 
  bucket_path: "bcdocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY